RailwayApp/RailwayApp/Controllers/AdminController.cs
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace RailwayApp.Controllers;

public class AdminController : Controller
{
    private INewsTableService _newsService;
    private IRailwayStaffService _staffService;

    public AdminController(INewsTableService newsService, IRailwayStaffService staffService)
    {
        _newsService = newsService;
        _staffService = staffService;
    }
    
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult ShowAllStaff()
    {
        var items = _staffService.GetAll();
        return View(items);
    }

    [HttpGet]
    public IActionResult CreateStaff()
    {
        ViewBag.Staff = _staffService.GetAll();
        return View();
    }
    [HttpPost]
    public IActionResult CreateStaff(RailwayStaffDTO item)
    {
        ViewBag.Staff = _staffService.GetAll();
        if (ModelState.IsValid)
        {
            ViewBag.Message = "Valid";
            _staffService.Add(item);
            return RedirectToAction(nameof(ShowAllStaff));
        }
        ViewBag.Message = "Non Valid";
        return View(item);
    }
    
    [HttpGet]
    public IActionResult UpdateStaff(int id)
    {
        var item = _staffService.GetById(id);
        return View(item);
    }
    [HttpPost]
    public IActionResult UpdateStaff(RailwayStaffDTO item)
    {
        if (ModelState.IsValid)
        {
            ViewBag.Message = "Valid";
            _staffService.Update(item);
            return RedirectToAction(nameof(ShowAllStaff));
        }
        ViewBag.Message = "Non Valid";
        return View(item);
    }
    
    public IActionResult DeleteStaff(int id)
    {
        var item = _staffService.GetById(id);
        if (item == null) 
            RedirectToAction(nameof(ShowAllStaff));
        return View(item);
    }
    [HttpPost]
    public IActionResult DeleteStaff(RailwayStaffDTO item)
    {
        _staffService.Delete(item.Id);
        return RedirectToAction(nameof(ShowAllStaff));
    }
    
    public IActionResult ShowAllNews()
    {
        var items = _newsService.GetAll();
        return View(items);
    }
    
    [HttpGet]
    public IActionResult CreateNews()
    {
        ViewBag.News = _newsService.GetAll();
        return View();
    }
    [HttpPost]
    public IActionResult CreateNews(NewsTableDTO item)
    {
        ViewBag.News = _newsService.GetAll();
        if (ModelState.IsValid)
        {
            ViewBag.Message = "Valid";
            _newsService.Add(item);
            return RedirectToAction(nameof(ShowAllNews));
        }
        ViewBag.Message = "Non Valid";
        return View(item);
    }
    
    [HttpGet]
    public IActionResult UpdateNews(int id)
    {
        var item = _newsService.GetById(id);
        return View(item);
    }
    [HttpPost]
    public IActionResult UpdateNews(NewsTableDTO item)
    {
        if (ModelState.IsValid)
        {
            ViewBag.Message = "Valid";
            _newsService.Update(item);
            return RedirectToAction(nameof(ShowAllNews));
        }
        ViewBag.Message = "Non Valid";
        return View(item);
    }
    
    public IActionResult DeleteNews(int id)
    {
        var item = _newsService.GetById(id);
        if (item == null) 
            RedirectToAction(nameof(ShowAllNews));
        return View(item);
    }
    [HttpPost]
    public IActionResult DeleteNews(NewsTableDTO item)
    {
        _newsService.Delete(item.Id);
        return RedirectToAction(nameof(ShowAllNews));
    }

    public IActionResult Exit()
    {
       return RedirectToAction("Index", "Home");
    }
}

RailwayApp/RailwayApp/Controllers/ClientController.cs
using System.Text.Json;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using RailwayApp.Models;

namespace RailwayApp.Controllers;

public class ClientController : Controller
{
    private string pathForClients =
        "E:\\Учёба Университет\\ИГИ\\Курсовая работа\\RailwayApp\\RailwayApp\\ClientData.json";
    private IStationService _stationService;
    private ICountryService _countryService;
    private ITrainService _trainService;
    private INewsTableService _newsTableService;
    private IRouteStopService _routeStopService;
    private ITicketService _ticketService;
    private IRouteService _routeService;
    private IClientService _clientService;
    
    public ClientController(INewsTableService newsTableService, ITrainService trainService, ICountryService countryService,
        IStationService stationService, IRouteStopService routeStopService, IRouteService routeService, IClientService clientService,
        ITicketService ticketService)
    {
        _stationService = stationService;
        _newsTableService = newsTableService;
        _trainService = trainService;
        _countryService = countryService;
        _routeStopService = routeStopService;
        _routeService = routeService;
        _clientService = clientService;
        _ticketService = ticketService;
    }
    public IActionResult Index(int id)
    {
        var json = JsonSerializer.Serialize(id);
        System.IO.File.WriteAllText(pathForClients, json);
        var news = _newsTableService.GetAll();
        var stations = _stationService.GetAll();
        ViewBag.Stations = new SelectList(stations, "Id", "Name");
        return View(news);
    }

    [HttpPost]
    public IActionResult Index(string DepartureName, string ArrivalName, DateOnly DateRoute)
    {
        if (DepartureName.IsNullOrEmpty() || ArrivalName.IsNullOrEmpty())
        {
            var news = _newsTableService.GetAll();
            var stations = _stationService.GetAll();
            ViewBag.Stations = new SelectList(stations, "Id", "Name");
            ViewBag.ErrorMessage = "Произошла ошибка! Пожалуйста, повторите попытку.";
            return View(news);
        }
        else
        {
            var departureStation = _stationService.GetAll().FirstOrDefault(s => s.Id == int.Parse(DepartureName));
            var arrivalStation = _stationService.GetAll().FirstOrDefault(s => s.Id == int.Parse(ArrivalName));
            
            var departureRouteStops = _routeStopService.GetAll().Where(rs => rs.StationId == departureStation.Id && rs.DepartureDate == DateRoute);
            var arrivalRouteStops = _routeStopService.GetAll().Where(rs => rs.StationId == arrivalStation.Id);
            if (departureRouteStops.Count() == 0 || arrivalRouteStops.Count() == 0)
            {
                var news = _newsTableService.GetAll();
                var stations = _stationService.GetAll();
                ViewBag.Stations = new SelectList(stations, "Id", "Name");
                ViewBag.ErrorMessage = "Произошла ошибка! Пожалуйста, повторите попытку.";
                return View(news);
            }
            var commonRoutes = departureRouteStops.Join(
                    arrivalRouteStops,
                    departure => departure.RouteId,
                    arrival => arrival.RouteId,
                    (departure, arrival) => departure.RouteId)
                .ToList();
            var json = JsonSerializer.Serialize(commonRoutes);
            TempData["CommonRoutes"] = json;
            return RedirectToAction(nameof(ShowAllNeedRoutes), new { DepartureName = departureStation.Name, ArrivalName = arrivalStation.Name});
        }
    }

    public IActionResult ShowAllNeedRoutes(string DepartureName, string ArrivalName)
    {
        var IDs = TempData["CommonRoutes"] as string;
        var needIdsInt = JsonSerializer.Deserialize<List<int>>(IDs);
        var cr = _routeService.GetAllWithAnotherData().Where(obj => needIdsInt.Contains(obj.Id)).ToList();
        var allNeedRoutes = _routeService.GetAllWithAnotherData();
        var anr = allNeedRoutes    
            .Where(r => cr.Select(n => n.Id).Contains(r.Id));
        OwnClientRouteViewModel ocrvm = new OwnClientRouteViewModel(anr, DepartureName, ArrivalName); 
        return View(ocrvm);
    }

    public IActionResult AboutRoute(int id, string DepartureName, string ArrivalName)
    {
        var myRoute = _routeService.GetAllWithAnotherData().FirstOrDefault(r => r.Id == id);
        return View(myRoute);
    }

    public IActionResult BookingRoute(int id, string DepartureName, string ArrivalName)
    {
        var myRoute = _routeService.GetAllWithAnotherData().FirstOrDefault(r => r.Id == id);
        var CountPlaces = myRoute.Train.CarriageCount * myRoute.Train.Carriage.PlacesCount;
        if (myRoute.Tickets.Count() == CountPlaces)
        {
            ViewBag.Message = "Кажется, все билеты на поезд уже забронированы.";
        }
        else
        {
            var json = System.IO.File.ReadAllText(pathForClients);
            ClientDTO client = _clientService.GetById(JsonSerializer.Deserialize<int>(json));
            Random random = new Random();
            ViewBag.Message = "Бронирование успешно выполнено.";
            TicketDTO ticket = new TicketDTO();
            ticket.RouteId = myRoute.Id;
            ticket.TicketPrice = (myRoute.FullRoutePrice / myRoute.RouteStops.LastOrDefault().SequenceNumber) * myRoute.RouteStops.FirstOrDefault(s => s.Station.Name == ArrivalName).SequenceNumber;
            ticket.DepartureStation = DepartureName;
            ticket.ArrivalStation = ArrivalName;
            ticket.SeatNumber = random.Next(1, myRoute.Train.CarriageCount * myRoute.Train.Carriage.PlacesCount);
            ticket.ClientId = client.Id;
            _ticketService.Add(ticket);
        }
        return View();
    }

    public IActionResult ShowMyBagRoutes()
    {
        var json = System.IO.File.ReadAllText(pathForClients);
        ClientDTO client = _clientService.GetById(JsonSerializer.Deserialize<int>(json));
        var ticket = _ticketService.GetAll().FirstOrDefault(t => t.ClientId == client.Id);
        TicketRouteViewModel trvm = null;
        if (ticket == null)
            ViewBag.Message = "На данный момент корзина пуста.";
        else
        {
            var myRoute = _routeService.GetAllWithAnotherData().FirstOrDefault(r => r.Id == ticket.RouteId);
            trvm = new TicketRouteViewModel(ticket, myRoute);
        }
        return View(trvm);
    }
    public IActionResult ShowAllTrains()
    {
        var trains = _trainService.GetAllWithTypes();
        return View(trains);
    }

    public IActionResult ShowAllServices()
    {
        return View();
    }

    public IActionResult ShowOurDataAndFriends()
    {
        var countries = _countryService.GetAll();
        return View(countries);
    }
}

RailwayApp/RailwayApp/Views/Shared/Success.cshtml
@{
    Layout = "_ClientLayout";
}
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="successModalLabel">Успешное бронирование</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Ваш маршрут успешно забронирован!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

RailwayApp/RailwayApp/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RailwayApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RailwayApp.styles.css" asp-append-version="true"/>
    <style>
        .carousel-item img {
            border-color: #6a1a21;
            border-radius: 3px;
        }
        
        .my-carousel {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" alt="Железная дорога" width="70" height="50" class="d-inline-block align-top" />
                Hedgehog Railway
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Новости</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Информация о нас
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Home" asp-action="ShowAllTrains">Наши поезда</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="ShowAllServices">Наши услуги и рейтинги</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="ShowOurDataAndFriends">О нас и наших друзьях</a>
                        </div>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Authorization">
                            <img src="~/images/user.png" alt="Пользователь" width="30" height="30" class="d-inline-block align-top" />
                            Войти
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Hedgehog Railway Company - Все права защищены.
        Наши контакты - <a href="https://vk.com/al_feed.php"> автор сайта</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RailwayApp/RailwayApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RailwayApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @*<link rel="stylesheet" href="~/RailwayApp.styles.css" asp-append-version="true"/>*@
</head>
<body>
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Admin" asp-action="Index">
            <img src="~/images/logo.png" alt="Железная дорога" width="70" height="50" class="d-inline-block align-top" />
            Hedgehog Railway
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="ShowAllStaff">Сотрудники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="ShowAllNews">Новости</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Администратор
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Exit">
                        <img src="~/images/exit.png" alt="Пользователь" width="30" height="30" class="d-inline-block align-top"/>
                        Выйти
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Hedgehog Railway Company - Все права защищены.
        <p>Наши контакты - <a href="https://vk.com/al_feed.php"> автор сайта</a></p>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RailwayApp/RailwayApp/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RailwayApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RailwayApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Client" asp-action="Index">
                <img src="~/images/logo.png" alt="Железная дорога" width="70" height="50" class="d-inline-block align-top" />
                Hedgehog Railway
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#news">Новости</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Информация о нас
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Client" asp-action="ShowAllTrains">Наши поезда</a>
                            <a class="dropdown-item" asp-controller="Client" asp-action="ShowAllServices">Наши услуги и рейтинги</a>
                            <a class="dropdown-item" asp-controller="Client" asp-action="ShowOurDataAndFriends">О нас и наших друзьях</a>
                        </div>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Клиент
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Client" asp-action="ShowMyBagRoutes">
                            <i class="bi bi-cart"></i>
                            Корзина
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <img src="~/images/exit.png" alt="Пользователь" width="30" height="30" class="d-inline-block align-top"/>
                            Выйти
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<div class="container-fluid">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Hedgehog Railway Company - Все права защищены.
        Наши контакты - <a href="https://vk.com/al_feed.php"> автор сайта</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RailwayApp/RailwayApp/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RailwayApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RailwayApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light bg-gradient">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Manager" asp-action="Index">
            <img src="~/images/logo.png" alt="Железная дорога" width="70" height="50" class="d-inline-block align-top" />
            Hedgehog Railway
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Manager" asp-action="ShowAllRoutes">Маршруты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Транспорт
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllTrains">Поезда</a>
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllTypeTrain">Типы поездов</a>
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllCarriages">Вагоны</a>
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllTypeCarriage">Типы вагонов</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Остановки
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllCountries">Страны</a>
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllCities">Города</a>
                        <a class="dropdown-item" asp-controller="Manager" asp-action="ShowAllStations">Станции</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Отчетность
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Manager" asp-action="PopulationDiagram">Популярные маршруты</a>
                    </div>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Менеджер
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Exit">
                        <img src="~/images/exit.png" alt="Пользователь" width="30" height="30" class="d-inline-block align-top"/>
                        Выйти
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Hedgehog Railway Company - Все права защищены.
        <p>Наши контакты - <a href="https://vk.com/al_feed.php"> автор сайта</a></p>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>